[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "HTk3g5v5CUai7MXF3r87jAMDjpGH6oXFJQCRYf4GFrv9"

[programs.devnet]
escrow = "HTk3g5v5CUai7MXF3r87jAMDjpGH6oXFJQCRYf4GFrv9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
